spring.application.name=customer-service
server.port=8082
#spring.datasource.url= jdbc:h2:mem:customers-db
#spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/customers_db
spring.datasource.username=postgres
spring.datasource.password=tanguydev
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
