spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ebank-realm
  cloud:
    config:
      import: optional:configserver:http://localhost:9999
      fail-fast: false
      retry:
        max-attempts: 3
        initial-interval: 1000
    gateway:
      server:
        webflux:
          globalcors:
           cors-configurations:
             '[/**]':
               allowedOrigins: "http://localhost:4200"
               allowedMethods: "*"
               allowedHeaders: "*"
               allowCredentials: 'true'
               maxAge: 3600
          default-filters:
            - TokenRelay
#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: r1
#              uri: http://localhost:8082
#              predicates:
#                - Path=/api/customers/**
#            - id: r2
#              uri: http://localhost:8083
#              predicates:
#                - Path=/api/accounts/**