spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/ebank-realm}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/CUSTOMER-SERVICE/**
          filters:
            - RewritePath=/CUSTOMER-SERVICE/(?<segment>.*), /${segment}
            - TokenRelay
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:86"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: 'true'
                maxAge: 3600
          default-filters:
            - TokenRelay
#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: r1
#              uri: http://localhost:8082
#              predicates:
#                - Path=/api/customers/**
#            - id: r2
#              uri: http://localhost:8083
#              predicates:
#                - Path=/api/accounts/**