spring.application.name=ebank-bot
server.port=8084
spring.ai.openai.api-key= REMOVEDproj-ADJJ_lzdHbuJhsfeIehM2k8XjQ9Tp1Bt0LcqNKmZLu2awVuOqbd9mY0-NEkqjgjCjsg4LX5Kj7T3BlbkFJ55uBwwc-LLaQ40IB5nRp2hjlx4VdPnYvNNXbDiJWD-I2O8wBMRyvjYbDdvj5UZRV0rSjEc5JAA
spring.ai.openai.chat.model=gpt-4o
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false

spring.ai.mcp.client.streamable-http.connections.customer-service.url=http://localhost:8082
spring.ai.mcp.client.streamable-http.connections.ebank-service.url=http://localhost:8083