spring.application.name=ebank-bot

spring.ai.openai.api-key= REMOVEDproj-1Zdb4_5mfjeF9N1wLTs5t2W1519BEcbdkZ1QYr3jObk0cR05R--ma0uLlIajFdcFNe6c6L2FqxT3BlbkFJ-LvJ1446WTPezx-AMTWHGlPBWzMpgjuTGLIshFYXAQhAOx8ixbI0a8IxzM7E1stI6n5lRMH24A
spring.ai.openai.chat.model=gpt-4o
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false