spring.application.name=ebank-service
server.port=8083
spring.datasource.url= jdbc:h2:mem:ebank-db
spring.h2.console.enabled=true
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

